// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: coroot/service/v1/rpc.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerSpanService_Upload_FullMethodName = "/coroot.service.v1.ServerSpanService/Upload"
)

// ServerSpanServiceClient is the client API for ServerSpanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerSpanServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse], error)
}

type serverSpanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServerSpanServiceClient(cc grpc.ClientConnInterface) ServerSpanServiceClient {
	return &serverSpanServiceClient{cc}
}

func (c *serverSpanServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServerSpanService_ServiceDesc.Streams[0], ServerSpanService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerSpanService_UploadClient = grpc.ClientStreamingClient[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]

// ServerSpanServiceServer is the server API for ServerSpanService service.
// All implementations must embed UnimplementedServerSpanServiceServer
// for forward compatibility.
type ServerSpanServiceServer interface {
	Upload(grpc.ClientStreamingServer[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]) error
	mustEmbedUnimplementedServerSpanServiceServer()
}

// UnimplementedServerSpanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerSpanServiceServer struct{}

func (UnimplementedServerSpanServiceServer) Upload(grpc.ClientStreamingServer[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedServerSpanServiceServer) mustEmbedUnimplementedServerSpanServiceServer() {}
func (UnimplementedServerSpanServiceServer) testEmbeddedByValue()                           {}

// UnsafeServerSpanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerSpanServiceServer will
// result in compilation errors.
type UnsafeServerSpanServiceServer interface {
	mustEmbedUnimplementedServerSpanServiceServer()
}

func RegisterServerSpanServiceServer(s grpc.ServiceRegistrar, srv ServerSpanServiceServer) {
	// If the following call pancis, it indicates UnimplementedServerSpanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerSpanService_ServiceDesc, srv)
}

func _ServerSpanService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServerSpanServiceServer).Upload(&grpc.GenericServerStream[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServerSpanService_UploadServer = grpc.ClientStreamingServer[ServerSpanServiceUploadRequest, ServerSpanServiceUploadResponse]

// ServerSpanService_ServiceDesc is the grpc.ServiceDesc for ServerSpanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerSpanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coroot.service.v1.ServerSpanService",
	HandlerType: (*ServerSpanServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _ServerSpanService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "coroot/service/v1/rpc.proto",
}
